### ISSUE TITLE
Works partially

### ISSUE THREAD

**Issue by marcselman** [macabeus/vscode-fluent#17]
Hi, I'm trying to use the extension but not everything seems to work for me.
I've created an empty project with just a simple Typescript file and a Fluent file.

What works:
- Syntax highlight
- Show syntax errors

What does not work:
- Code Action to extract a string to Fluent files (menu item does not show)
- Hover support on messages (no tooltip)
- Breadcrumbs support (just the file path breadcrumb)
- Go to message definition from a reference

Am I missing something or doing something wrong?

**Comment by macabeus** [comment]
@marcselman Thanks for open this issue.
I checked now, and it looks like that some new VSCode version broke the extension =/

I can try to fix it later, but if you could help me would be nice. I'm not using Fluent for a while, and so I didn't notice before that the extension was broken.

**Comment by marcselman** [comment]
Sure, I have no experience with writing VS Code plugins. How can I help?

**Comment by macabeus** [comment]
You can clone this repository, open the code source on your VSCode and then run the debugger. It'll open a new VSCode instance with the extension running. It should work out of the box.

The features that aren't working are provided by the [`active`](https://github.com/macabeus/vscode-fluent/blob/f55e9ef16b0cba6dad9d7cacac996ae6d2ac23fe/src/extension.ts#L10) function. So you could check why it's working correctly.
You can set a breakpoint there, check if there are some errors raising or something like that.

I'm guessing that it isn't working anymore because of [Workspace Trust](https://code.visualstudio.com/docs/editor/workspace-trust) - but it's just a guess.

**Comment by macabeus** [comment]
@marcselman Hey, I released a new version. Please, can you check if it fixed the issue?

**Comment by marcselman** [comment]
@macabeus Tested, and works great now! Sorry that I didn't find time to help you out. But thanks for fixing it!
